"""Init

Revision ID: 64d512e18d64
Revises: 5c7828f3917c
Create Date: 2026-04-05 18:38:49.404314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d512e18d64'
down_revision = '5c7828f3917c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('khs_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rekomendasi_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('khs_uploads', schema=None) as batch_op:
        batch_op.drop_column('rekomendasi_json')

    # ### end Alembic commands ###
